### PR TITLE
Configure tx_count and the heartbeat timeout via flags

### LINKED ISSUE #5: Unnecessary heartbeat timeout when using PIM-IP directly
When using a TCP connection to the PIM-IP from Pulseworx, the connection code always schedules a heartbeat check every 90 seconds.  That works when using ser2tcp, but with such a direct connection the PIM does not provide any heartbeat traffic, so upb_lib constantly closes, reopens, and scans the whole network to assess state again every 90 seconds.

Things are even worse in Home Assistant’s UPB integration which uses added callbacks on the reconnection to establish link and scene integration each reconnection cycle.

Suggestion: allow heartbeat time to be overridden with a configuration option to the UpbPim() class.  Or add it as a parsable flag on the TCP url, something like tcp://1.2.3.4[:port][?heartbeat_time=xxx[,name=val]*].

### PR DESCRIPTION
**Pull request by mag1024**
tx count of 2 seems to be required for the devices on my network to respond.
I don't know for sure, but I suspect it is related to the presence of a repeater. 
I found this oblique reference in the some [repeater documentation](https://www.smarthome-products.com/productspecs/HAI/39A00-3_Manual.pdf) that corroborates this theory:

> UPStart normally uses uni-packet transmissions to communicate to UPB™ devices however, once the TPR is added to the network, it will automatically switch to using multi-packet transmissions. UPStart indicates that it has switched to two-time multi-packets by displaying TX=2 in the status bar. 

While I was at it, I also added the ability to configure the heartbeat timeout for TCP as requested in #5. It was also triggering for me spuriously.

Closes #5

### CODE REVIEW

**Comment by gwww** [comment]
Thanks! I'm reviewing the code now.

How have you tested these changes?

Are you planning on updated the config_flow in HA with options? If so, please use the current values for TX and heartbeat as the default.

**Comment by mag1024** [comment]
I tested by running a local Home Assistant instance with a hacked up upb integration -- I guess I'll need to upstream those changes as well. Seems like these kind of parameters might be better off as an Options rather than a Config flow.
Either way will keep the tx count defaulting to 1 -- and won't expose the deadline explicitly at all. Might just make a "flags" text box.

**Comment by gwww** [comment]
Sounds good. Options is right on. I'm OK if you just expose TX count. Probably should not expose flags as a general field is my sense. I'll look some more at the code over the weekend... no time to review right now. If you get started on the option(s) in HA I'll see that code too. Thanks again!

**Comment by gwww** [comment]
Thanks!

**Comment by gwww** [comment]
I just published 0.5 to PyPi. I have reviewed the code and seems OK. I'm not in a position to test the on my UPB network until later this week, so I relying on you to test.

**Pull request merged**
